{
  "comments": [
    {
      "key": {
        "uuid": "eaa6cdef_cca9c91e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 17092
      },
      "writtenOn": "2020-09-01T13:59:10Z",
      "side": 1,
      "message": "Test failures are due to golang.org/issue/41146. If you rebase and run the trybots again, they should pass.",
      "revId": "3d145dd30f238ec07a3c4d66791d0b1dcd49032f",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705",
      "unresolved": false
    }
  ]
}